### ISSUE TITLE
Equatable doesn't work with List prop

### ISSUE THREAD

**Issue by ThangVuNguyenViet** [felangel/equatable#64] opened 2020-04-28 18:33 UTC
`class EquatableStrings extends Equatable{
  final List<String> strings;
  const EquatableStrings({this.strings});

  @override
  List<Object> get props => [strings];
}

EquatableStrings(['a']) == EquatableStrings(['b']) //true
['a'] == ['b'] // false, obviously`

I expect the first comparison to be false, as the prop inside it was different. Is there something that I'm missing?
I'm working with flutter_bloc, which I have a state that contains a list item. When I try to modify that list and yield new state, it does not update, as the two states are equal

**Comment by felangel** [comment] 2020-04-28 18:36
Hi @ThangVuNguyenViet 👋 
Thanks for opening an issue!

I suspect the problem is your list is of type dynamic.

Can you try adjusting your class to:

```dart
class EquatableStrings extends Equatable{
  final List<String> strings;
  const EquatableStrings({this.strings});

  @override
  List<Object> get props => [strings];
}
```

**Comment by felangel** [comment] 2020-05-10 00:54
Closing for now but feel free to comment with additional questions/information and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-05-10 00:54 UTC
Labels: question, waiting for response

**Comment by JohnGalt1717** [comment] 2020-09-10 21:10
I'm also getting this and I have it defined as:

final List<EmailAddressState> emailAddresses;

@override
  List<Object> get props => [status, errorMessage, emailAddresses, contact];

EmailAddressState also implements equatable so any change to any element in the List should trigger inequality or an add/remove to or from the list should do the same.

It appears to work on updating, but it doesn't appear to work on add/remove.
