### ISSUE TITLE
Allow usage EquatableMixin for mutable classes

### ISSUE THREAD

**Issue by slavap** [felangel/equatable#186] opened 2024-11-21 06:55 UTC
In version 2.0.6 EquatableMixin was changed to include immutable annotation.
IMO this is the wrong change, because now it is impossible to use this mixin for mutable classes - in "general" this is wrong pattern, but classes are "late immutable", i.e. they are declared without final for fields, but first instantiated and populated by data, and after that never changing, so it is safe to use EquatableMixin.
At least add new mixin EquatableMixinUnsafe without immutable annotation, so in code I can decide when to use equatable without the need to suppress linter warnings.

**Comment by felangel** [comment] 2024-11-21 16:10
You should not use Equatable with mutable classes. This has been mentioned explicitly in the README for a long time:

> **Note:** Equatable is designed to only work with immutable objects so all member variables must be final (This is not just a feature of `Equatable` - [overriding a `hashCode` with a mutable value can break hash-based collections](https://dart.dev/guides/language/effective-dart/design#avoid-defining-custom-equality-for-mutable-classes)).

**Comment by slavap** [comment] 2024-11-22 00:50
@felangel 
**late final** is quite a bad thing, easy to be "clean" on compile and then get RUNTIME errors.
Example:
```dart
class MyData {
  late final int id;
  late final String code;
  late final String? param1;
  late final String? param2;
  late final String? param3;
}

Future<void> populate() async {
  final d = MyData();
  d.param1 = 'aaa';
  d.param1 =
      'bbb'; // << RUNTIME ERROR, DartError: LateInitializationError: Field 'param1' has already been initialized.

  d.id = await service1.getMyId();
  d.code = await service2.getMyCode(d.id);
  d.param1 = await service3.getMyParam(d.id);
  d.param2 = await service4.getMyParam(d.id, d.param1);
  d.param3 = await service5.getMyParam(d.id, d.param1, d.param2);
  
  // Then not here, but much later in a different place the following happens as the last initialization step:
  final (String, String, String) r = await service6.getMyData(d.id, d.code, d.param1, d.param2, d.param3);
  d.param1 = r.$1;
  d.param2 = r.$2;
  d.param3 = r.$3;
}
```

**Comment by felangel** [comment] 2024-11-22 04:15
> @felangel **late final** is quite a bad thing, easy to be "clean" on compile and then get RUNTIME errors. Example:
> 
> ```dart
> class MyData {
>   late final int id;
>   late final String code;
>   late final String? param1;
>   late final String? param2;
>   late final String? param3;
> }
> 
> Future<void> populate() async {
>   final d = MyData();
>   d.param1 = 'aaa';
>   d.param1 =
>       'bbb'; // << RUNTIME ERROR, DartError: LateInitializationError: Field 'param1' has already been initialized.
> 
>   d.id = await service1.getMyId();
>   d.code = await service2.getMyCode(d.id);
>   d.param1 = await service3.getMyParam(d.id);
>   d.param2 = await service4.getMyParam(d.id, d.param1);
>   d.param3 = await service5.getMyParam(d.id, d.param1, d.param2);
>   
>   // Then not here, but much later in a different place the following happens as the last initialization step:
>   final (String, String, String) r = await service6.getMyData(d.id, d.code, d.param1, d.param2, d.param3);
>   d.param1 = r.$1;
>   d.param2 = r.$2;
>   d.param3 = r.$3;
> }
> ```

late final is exactly designed for the case you described where a variable is initialized late but never changes afterwards.

Can you share some code that illustrates your current approach?

**Comment by slavap** [comment] 2024-11-22 05:36
@felangel My previous example already illustrates my approach. 
Let me explain it more, and also why "late final" is not suitable there.
```dart
d.param3 = await service5.getMyParam(d.id, d.param1, d.param2);
```
At some point during data loading and processing d.param3 is assigned - so "late final" is "done", the next attempt to assign will raise RUNTIME error.
But "loading and processing" is not yet completed, after multiple steps LATER d.param3 value need to be reassigned:
```dart
final (String, String, String) r = await service6.getMyData(d.id, d.code, d.param1, d.param2, d.param3);
d.param3 = r.$3;
```
Of course I can replace d by clone with new values assigned, but: clone is performance hit AND my code expects that d will remain the same instance.

**Comment by felangel** [comment] 2024-11-27 19:51
> @felangel My previous example already illustrates my approach. Let me explain it more, and also why "late final" is not suitable there.
> 
> ```dart
> d.param3 = await service5.getMyParam(d.id, d.param1, d.param2);
> ```
> 
> At some point during data loading and processing d.param3 is assigned - so "late final" is "done", the next attempt to assign will raise RUNTIME error. But "loading and processing" is not yet completed, after multiple steps LATER d.param3 value need to be reassigned:
> 
> ```dart
> final (String, String, String) r = await service6.getMyData(d.id, d.code, d.param1, d.param2, d.param3);
> d.param3 = r.$3;
> ```
> 
> Of course I can replace d by clone with new values assigned, but: clone is performance hit AND my code expects that d will remain the same instance.

In that case I recommend implementing your own equality checks rather than using Equatable. Equatable is specifically for immutable classes. If you can share a full minimal reproduction sample I'm happy to take a few minutes to refactor it so that you can use Equatable but closing this for now since there aren't any actionable next steps.

**Closed by felangel** 2024-11-27 19:51 UTC
Labels: question, waiting for response
