### ISSUE TITLE
Equatable for List<Object> doesn't work

### ISSUE THREAD

**Issue by c0c4i** [felangel/equatable#121] opened 2021-06-08 12:13 UTC
**Describe the bug**
I have a `List<Step>` inside my class where `Step` is extended with Equatable.
But when I dispatch a new state (same as the previous) but with a different Step inside List it doesn't update

**Expected behavior**
A new state with different Step on my List

**Version**
Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "macos_x64"

**Comment by felangel** [comment] 2021-06-08 15:15
Hi @c0c4i 👋 
Thanks for opening an issue!

Can you please provide a minimal reproduction sample so that I can debug the issue locally? Thanks 🙏

**Comment by felangel** [comment] 2021-06-14 04:42
Closing for now since there isn't a reproduction sample. Feel free to provide a link to a minimal reproduction sample and I'm happy to take a closer look 👍

**Closed by felangel** 2021-06-14 04:42 UTC
Labels: question, waiting for response
